# Generated by Django 4.1.5 on 2023-03-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='tc',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('rId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('remark', models.TextField(max_length=255)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employment')),
            ],
        ),
    ]
