# Generated by Django 4.1.5 on 2023-03-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_admin_tc_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='file',
        ),
        migrations.AddField(
            model_name='employment',
            name='resume',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='resume/'),
        ),
    ]
