# Generated by Django 4.1.5 on 2023-03-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_response_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Remark',
        ),
    ]
