# Generated by Django 4.1.5 on 2023-03-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_response_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('aId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('desirejob', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(default=None, max_length=255, null=True, upload_to='resume/')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
